- name: Check if environment is set
  hosts: all
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."


- name: Setup project
  hosts: all
  roles:
    - name: ../roles/setup
  tags:
    - setup


- name: Config project
  hosts: all
  roles:
    - name: ../roles/config
  tags:
    - config
