all:
  hosts:
    ofrf-dev@TKGI:
      ansible_python_interpreter: python3
      ansible_host: localhost
      ansible_connection: local
      tkgi_clustername: svc0056mprntkd0001
      tkgi_apiserver: tkgi.epfl.ch

      ### Secrets env vars ######################################
      _ofrf_secrets: "{{ lookup('file', '/keybase/team/epfl_idevfsd/ofrf/secrets-dev.yml') | from_yaml }}"

  vars:
    RUNINFRA: k8s
    RUNENV: dev
    _harbor_pull_credential: "{{ _ofrf_secrets.harbor.pull_robot.name }}:{{ _ofrf_secrets.harbor.pull_robot.token }}"
    harbor_pull_config:
      auths:
        "vsissp-harbor-p.epfl.ch":
          "auth": "{{ _harbor_pull_credential | b64encode }}"

