all:
  hosts:
    itsmprnt0017:
      ansible_host: 10.95.64.36
      ansible_port: 22
      ansible_user: ubuntu
      web_server_msg: "Hello, this is the test server itsmprnt0017"

      ### Secrets env vars ######################################
      _ofrf_secrets: "{{ lookup('file', '/keybase/team/epfl_idevfsd/ofrf/secrets-test.yml') | from_yaml }}"

  vars:
    RUNINFRA: vm
    RUNENV: test
