## Manage /etc/odbc.ini

- name: Create {{ ofrf_home }} if it does not exist
  ansible.builtin.file:
    path: "{{ ofrf_home }}"
    state: directory


- name: Add FreeTDS config into odbc.ini
  ansible.builtin.copy:
    content: |
      [FreeTDS]
      Description=FreeTDS Driver
      Driver=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
      Setup=/usr/lib/x86_64-linux-gnu/odbc/libtdsS.so
      CPTimeout=
      CPReuse=
    dest: "{{ ofrf_home }}/odbc.ini"


## Manage /etc/odbcinst.ini

- name: Add FreeTDS config into odbcinst.ini
  ansible.builtin.copy:
    content: |
      [FreeTDS]
      Description=TDS driver (Sybase/MS SQL)
      Driver=libtdsodbc.so
      Setup=libtdsS.so
      CPTimeout=
      CPReuse=
      UsageCount=2
    dest: "{{ ofrf_home }}/odbcinst.ini"
