# Manage bill directory
- name: Bill directory exists ?
  ansible.builtin.shell:
    cmd: docker exec -it bill2myprint-app sh -c "test -d /app/src/bill2myprint/media/pdf && echo 'It exists'"
  failed_when: false
  changed_when: false
  register: _bill_directory_exists

#- debug:
#    var: _bill_directory_exists
#
#- debug:
#    msg: "bill directory exist"
#  when: _bill_directory_exists.stdout == "It exists"
#
#- debug:
#    msg: "bill directory doesn't exist"
#  when: _bill_directory_exists.stdout == ""

- name: Create bill directory in src/bill2myprint
  ansible.builtin.shell: |
    docker exec -it bill2myprint-app mkdir /app/src/bill2myprint/media &&
    docker exec -it bill2myprint-app mkdir /app/src/bill2myprint/media/pdf &&
    docker exec -it bill2myprint-app chown 1000:1000 /app/src/bill2myprint/media &&
    docker exec -it bill2myprint-app chown 1000:1000 /app/src/bill2myprint/media/pdf
  when: _bill_directory_exists.stdout == ""