# Manage data directory; create /src/data if it doesn't exist
- name: Create data directory if it doesn't exist
  ansible.builtin.file:
    path: "/app/ofrf/src/data"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

# Manage data/dbproddump.sql file: copy if it doesn't exist
- name: Copy dbproddump.sql if it doesn't exist
  ansible.builtin.copy:
    src: ./data/dbproddump.sql
    dest: /app/ofrf/src/data/dbproddump.sql
    owner: ubuntu
    group: ubuntu
    mode: '0755'

# Manage dump for database: clone data if table is empty
- name: Users exist ?
  ansible.builtin.shell:
    cmd: docker exec local-mysql /bin/bash -c 'mysql  -h db ofrf -u ofrf -pofrf -e "SHOW tables;" 2>&1 | grep -v "Warning"'
  failed_when: false
  changed_when: false
  register: _tables_DB_exist

- debug:
    var: _tables_DB_exist

- debug:
    msg: "Tables exist"
  when: _tables_DB_exist.stdout != ""

- debug:
    msg: "Tables doesn't exist"
  when: _tables_DB_exist.stdout == ""

- name: Run fab clone
  ansible.builtin.shell:
    cmd: docker exec -it bill2myprint-app fab clone
  when: _tables_DB_exist.stdout == ""
