---

- name: Apply storage
  import_tasks:
    file: ./k8s/storage.yml
  tags:
    - apply-app-pvc


- name: Apply app deployment
  import_tasks:
    file: ./k8s/app-deployment.yml
  tags:
    - apply-app-deployment


- name: Apply app service
  import_tasks:
    file: ./k8s/app-service.yml
  tags:
    - apply-app-service


- name: Apply app service account
  import_tasks:
    file: ./k8s/app-serviceaccount.yml
  tags:
    - apply-app-service-account


- name: Apply db deployment
  import_tasks:
    file: ./k8s/db-deployment.yml
  tags:
    - apply-db-deployment
  when: runenv == 'dev' 


- name: Restore database from dump
  kubernetes.core.k8s_exec:
    namespace: "{{ openshift_namespace }}"
    pod: ofrf-mariadb
    command: mysql -h mariadb ofrf -u ofrf -pofrf < ../../../data/dbproddump.sql
  tags:
    - apply-db-restore
  when: runenv == 'dev'


- name: Apply db service
  import_tasks:
    file: ./k8s/db-service.yml
  tags:
    - apply-db-service
  when: runenv == 'dev' 


- name: Apply db service account
  import_tasks:
    file: ./k8s/db-serviceaccount.yml
  tags:
    - apply-db-service-account
  when: runenv == 'dev'   


- name: Apply nginx configmap
  import_tasks:
    file: ./k8s/nginx-configmap.yml
  tags:
    - apply-nginx-configmap


- name: Apply nginx deployment
  import_tasks:
    file: ./k8s/nginx-deployment.yml
  tags:
    - apply-nginx-deployment


- name: Apply nginx service
  import_tasks:
    file: ./k8s/nginx-service.yml
  tags:
    - apply-nginx-service


- name: Apply nginx service account
  import_tasks:
    file: ./k8s/nginx-serviceaccount.yml
  tags:
    - apply-nginx-service-account


- name: Apply nginx ingress
  import_tasks:
    file: ./k8s/nginx-routes.yml
  tags:
    - apply-nginx-ingress


- name: Apply quay robot account
  import_tasks:
    file: ./k8s/rbac-quay-robot-account.yml
  tags:
    - apply-rbac-quay-robot-account


- name: Apply quay robot account
  import_tasks:
    file: ./k8s/cronjob.yml
  when: runenv == 'prod'
  tags:
    - cronjob
