- name: Cloning repository (fab clone)
  import_tasks:
    file: fab-clone.yml
  tags:
    - fab-clone


- name: Symbolic link
  import_tasks:
    file: symbolic-link.yml
  tags:
    - symbolic-link


- name: Bill directory
  import_tasks:
    file: bills.yml
  tags:
    - bills-directory


- name: Migrate
  import_tasks:
    file: migrate.yml
  tags:
    - migrate


- name: Run server (runserver)
  import_tasks:
    file: runserver.yml
  tags:
    - runserver