- name: Create app container
  community.docker.docker_container:
    name: bill2myprint-app
    image: bill2myprint-app
    command: python src/manage.py runserver --settings="config.settings.docker-test" 0.0.0.0:8000
    hostname: app
    state: started
    restart_policy: 'unless-stopped'
    volumes:
      - /app/ofrf:/app
    ports:
      - 8008:8000
    container_default_behavior: no_defaults
    networks:
      - name: 'ofrf_network'
    network_mode: default
  tags:
    - go_app
  when: runenv == 'test'


- name: Create app container
  community.docker.docker_container:
    name: bill2myprint-app
    image: bill2myprint-app
    command: python src/manage.py runserver --settings="config.settings.docker-prod" 0.0.0.0:8000
    hostname: app
    state: started
    restart_policy: 'unless-stopped'
    volumes:
      - /app/ofrf:/app
      - "{{ ofrf_home }}/odbc.ini:/etc/odbc.ini"
      - "{{ ofrf_home }}/odbcinst.ini:/etc/odbcinst.ini"
    ports:
      - 8008:8000
    container_default_behavior: no_defaults
    networks:
      - name: 'ofrf_network'
    network_mode: default
  tags:
    - go_app
  when: runenv == 'prod'
