- name: Getting process IDs of the process
  pids:
      name: python
  register: _runserver_running

- debug:
    var: _runserver_running

- debug:
    msg: "runserver running"
  when: _runserver_running.pids != []

- debug:
    msg: "runserver doesn't run"
  when: _runserver_running.pids == []

- name: Run runserver
  ansible.builtin.shell:
    cmd: docker exec -t bill2myprint-app python src/manage.py runserver 0.0.0.0:8000 &
  when: _runserver_running.pids == []
