# Manage secrets.json

- debug:
    var: _ofrf_secrets


- name: Open secrets.json file
  shell: cat /app/ofrf/secrets.json
  failed_when: false
  changed_when: false
  register: _app_secrets

- debug:
    var: _app_secrets


- name: Search if db password is already in file
  debug: msg="No need to modify secrets file"
  when: _app_secrets.stdout.find(_ofrf_secrets["OUR_DB_PASSWORD"].replace('"', '')) != -1


- name: Create secrets.json since the current is not updated
  debug: msg="Need to modify secrets file"
  when: _app_secrets.stdout.find(_ofrf_secrets["OUR_DB_PASSWORD"].replace('"', '')) == -1


- name: Remove secrets.json since the current is not updated (delete file)
  ansible.builtin.file:
    path: /app/ofrf/secrets.json
    state: absent
  when: _app_secrets.stdout.find(_ofrf_secrets["OUR_DB_PASSWORD"].replace('"', '')) == -1


- name: Touch secrets.json
  ansible.builtin.file:
    path: /app/ofrf/secrets.json
    state: touch
    mode: u=rw,g=r,o=r
  when: _app_secrets.stdout.find(_ofrf_secrets["OUR_DB_PASSWORD"].replace('"', '')) == -1


- name: Put data in secrets.json since the current is not updated
  ansible.builtin.shell: |
    cat <<EOF >> /app/ofrf/secrets.json
    {
        "SECRET_KEY": "{{ _ofrf_secrets["SECRET_KEY"] }}",
        "OUR_DB_HOST": "{{ _ofrf_secrets["OUR_DB_HOST"] }}",
        "OUR_DB_NAME": "{{ _ofrf_secrets["OUR_DB_NAME"] }}",
        "OUR_DB_USER": "{{ _ofrf_secrets["OUR_DB_USER"] }}",
        "OUR_DB_PASSWORD": "{{ _ofrf_secrets["OUR_DB_PASSWORD"] }}",

        "MYPRINT_DB_HOST": "{{ _ofrf_secrets["MYPRINT_DB_HOST"] }}",
        "MYPRINT_DB_NAME": "{{ _ofrf_secrets["MYPRINT_DB_NAME"] }}",
        "MYPRINT_DB_USER": "{{ _ofrf_secrets["MYPRINT_DB_USER"] }}",
        "MYPRINT_DB_PASSWORD": "{{ _ofrf_secrets["MYPRINT_DB_PASSWORD"] }}",

        "CADI_DB_HOST": "{{ _ofrf_secrets["CADI_DB_HOST"] }}",
        "CADI_DB_NAME": "{{ _ofrf_secrets["CADI_DB_NAME"] }}",
        "CADI_DB_USER": "{{ _ofrf_secrets["CADI_DB_USER"] }}",
        "CADI_DB_PASSWORD": "{{ _ofrf_secrets["CADI_DB_PASSWORD"] }}"
    }
    EOF
  when: _app_secrets.stdout.find(_ofrf_secrets["OUR_DB_PASSWORD"].replace('"', '')) == -1


- name: Replace secrets.json in docker by the new one
  ansible.builtin.shell:
    cmd: docker cp /app/ofrf/secrets.json bill2myprint-app:/app/secrets.json
  when: _app_secrets.stdout.find(_ofrf_secrets["OUR_DB_PASSWORD"].replace('"', '')) == -1