- name: symbolic link exist ?
  ansible.builtin.shell:
    cmd: docker exec bill2myprint-app /bin/bash -c 'ls -al /app/src/config/settings/default.py 2>&1 | grep "/app/src/config/settings/dockercompose.py"' || true
  ignore_errors: true
  changed_when: false
  register: _ln_exist

- debug:
    var: _ln_exist

- debug:
    msg: "ln exist"
  when: _ln_exist.stdout != ""

- debug:
    msg: "ln doesn't exist"
  when: _ln_exist.stdout == ""

- name: Create default.py symbolic link from dockercompose.py
  ansible.builtin.shell:
    cmd: docker exec -it bill2myprint-app rm -f /app/src/config/settings/default.py && docker exec -it bill2myprint-app ln -s /app/src/config/settings/dockercompose.py /app/src/config/settings/default.py && docker exec -it bill2myprint-app chmod 755 /app/src/config/settings/default.py
  when: _ln_exist.stdout == ""