- name: Create app/service-account
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: ofrf-service-account
        namespace: "{{ openshift_namespace }}"
      imagePullSecrets:
        - name: "{{ _ofrf_secrets.quay.pull_robot.name }}"
