- name: Create app/service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: app-service
        namespace: "{{ openshift_namespace }}"
        labels:
          app: ofrf
      spec:
        ports:
          - name: django-port
            port: 8000
        type: ClusterIP
        selector:
          app: ofrf
