- name: Create nginx/service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-service
        namespace: "{{ openshift_namespace }}"
        labels:
          app: nginx
      spec:
        ports:
          - name: http-port
            port: 8080
            targetPort: 8080
        type: ClusterIP
        selector:
          app: nginx
