- name: Create nginx/service-account
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: ofrf-nginx-service-account
        namespace: ofrf
      imagePullSecrets:
        - name: harbor-pull-secret
