- name: Create rbac/harbor-pull-sealed-secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      data:
        .dockerconfigjson: eyJhdXRocyI6eyJ2c2lzc3AtaGFyYm9yLXAuZXBmbC5jaCI6eyJ1c2VybmFtZSI6InJvYm90JGl0c21wcm50ZCtzdmMwMDU2LXB1bGwtMTY5NDUyODA4NiIsInBhc3N3b3JkIjoiNFZpeWVIQXZXaGJzYVlyUEd2dmhISXROMHZiTDRHRzAiLCJhdXRoIjoiY205aWIzUWthWFJ6YlhCeWJuUmtLM04yWXpBd05UWXRjSFZzYkMweE5qazBOVEk0TURnMk9qUldhWGxsU0VGMlYyaGljMkZaY2xCSGRuWm9TRWwwVGpCMllrdzBSMGN3In19fQ==
      kind: Secret
      metadata:
        creationTimestamp: null
        name: harbor-pull-secret
        namespace: ofrf
      type: kubernetes.io/dockerconfigjson
