- name: Create rbac/harbor-pull-sealed-secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      data:
        .dockerconfigjson: "{{ harbor_pull_config | to_json | b64encode }}"
      kind: Secret
      metadata:
        creationTimestamp: null
        name: harbor-pull-secret
        namespace: ofrf
      type: kubernetes.io/dockerconfigjson
