- name: Create app/pvc
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ofrf-pvc
        namespace: "{{ openshift_namespace }}"
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: ""  
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi
        volumeName: "{{ openshift_clustername }}"
