- name: Build app (django) image
  community.docker.docker_image:
    name: bill2myprint-app
    build:
      path: '/app/ofrf'
      nocache: no
    source: build
  tags:
    - build_app


- name: Create app container
  community.docker.docker_container:
    name: bill2myprint-app
    image: bill2myprint-app
    hostname: app
    state: started
    restart_policy: 'unless-stopped'
    volumes:
      - /app/ofrf:/app
    ports:
      - 8008:8000
    container_default_behavior: no_defaults
    networks:
      - name: 'ofrf_network'
  tags:
    - go_app
