---

- name: Log in git repository
  docker_login:
    registry: ghcr.io
    username: "{{ _private_secrets.ghcrio.username }}"
    password: "{{ _private_secrets.ghcrio.password }}"
    reauthorize: yes
  changed_when: false


- name: Push image from github to Harbor
  docker_login:
    registry: vsissp-harbor-p.epfl.ch
    username: "{{ _private_secrets.gaspar.user }}"
    password: "{{ _private_secrets.gaspar.password }}"
    reauthorize: yes
  changed_when: false


- name: Clone bill2myprint repo
  git:
    repo: git@github.com:epfl-si/bill2myprint.git
    dest: /tmp/ofrf
    force: yes
#    version: fea-kubernetes
    accept_hostkey: yes
  tags:
    - git_clone
