---
- tags: all
  include_vars: setup-vars.yml


- name: Ajoute toutes les clefs ssh de la FSD
  ansible.builtin.shell:
    cmd: curl https://raw.githubusercontent.com/zuzu59/deploy-proxmox/master/get_ssh_key_fsd.sh | bash
    chdir: /home/ubuntu
  tags: [ never, init_ssh ]


- name: install useful packages
  apt:
    name:
      - unixodbc
      - unixodbc-dev
      - freetds-dev
      - tdsodbc
    state: present
    force_apt_get: yes
  become: yes
  tags:
    - install_packages


- name: Install python psutil package
  pip:
    name: psutil
    executable: pip3
  tags:
    - install_python_psutil


- name: Docker install
  import_tasks:
    file: docker-install.yml
  tags:
    - docker-install


- name: Création du dossier /app/ofrf
  ansible.builtin.file:
    path: "/app/ofrf"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: yes


- name: Clone bill2myprint repo
  git:
      repo: git@github.com:epfl-si/bill2myprint.git
      dest: /app/ofrf
      force: yes
      version: fea-docker-file
  tags:
    - git_clone


- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /app/ofrf
    recurse: yes
    mode: '0755'
  become: yes
  tags:
    - ofrf_change_mode


- name: app server install
  import_tasks:
    file: app-server.yml
  tags:
    - app-server-install


- name: db server install
  import_tasks:
    file: db-server.yml
  tags:
    - db-server-install
