---

- name: Apply VM files
  import_tasks:
    file: vm-apply-files.yml
  tags:
    - apply-files
  when: runinfra == 'vm'


- name: Apply K8s files
  import_tasks:
    file: k8s-apply-files.yml
  tags:
    - apply-files
  when: runinfra == 'k8s'

