- name: Move Dockerfile to /app/ofrf
  ansible.builtin.copy:
    src: /app/ofrf/docker/ansible/Dockerfile
    dest: /app/ofrf/Dockerfile
    remote_src: yes
  tags:
    - build_app


- name: Build Dockerfile to create app image
  community.docker.docker_image:
    name: bill2myprint-app
    build:
      path: '/app/ofrf/'
      nocache: no
    source: build
  tags:
    - build_app
